name: Terragrunt PR workflow

on:
  pull_request:
    paths:
      - 'iac/envs/caladan/**/*.hcl'   # all .hcl files under iac/envs/caladan
      - 'iac/_components/**'          # all files under iac/_components

jobs:
  terragrunt-plan:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      # 1️⃣ Configure AWS credentials (access key + secret key)
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ap-southeast-1

      # 2️⃣ Run Terragrunt Plan
      - name: Run Terragrunt Plan
        uses: gruntwork-io/terragrunt-action@v3
        with:
          tg_dir: ./iac/envs/caladan
          tg_command: run-all plan
          tg_add_approve: '1'       # add --auto-approve
          tg_version: '0.86.2'
          tofu_version: '1.6.0'
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
